config/routes.rb
Rails.application.routes.draw do
  resources :levels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/level.rb
class Level < ActiveRecord::Base
  validates :number, :presence => true

  def self.search_daily(search_daily)
    if search_daily
      Level.where(:date => "#{search_daily}")
    end
  end

  def self.search_month_to_date(search_month_to_date)
    if search_month_to_date
      start_date = Level.where(:date => "#{search_month_to_date}").first.date.at_beginning_of_month
      end_date = Level.where(:date => "#{search_month_to_date}").first.date
      date_range = start_date..end_date
      Level.where(:date => date_range)
    end
  end

  def self.search_monthly(search_monthly)
    if search_monthly
      start_date = Level.where(:date => "#{search_monthly}").first.date.at_beginning_of_month-1.month
      end_date = Level.where(:date => "#{search_monthly}").first.date.at_beginning_of_month-1
      Level.where(:date => start_date..end_date)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  def index
    @levels = Level.where(:date => Time.now.strftime("%Y-%m-%d"))
    @levels1 = Level.search_daily(params[:search_daily])
    @levels2 = Level.search_month_to_date(params[:search_month_to_date])
    @levels3 = Level.search_monthly(params[:search_monthly])
    render :index
  end

  def show
    @level = Level.find(params[:id])
    render :show
  end

  def new
   @level = Level.new
   render :new
 end

 def create
   @level = Level.new(level_params)
   @level.date= Time.now.strftime("%Y-%m-%d")
   if @level.save
     redirect_to  levels_path
   else
     render :new
   end
 end

 def destroy
  @level = Level.find(params[:id])
  @level.destroy
  respond_to do |format|
    format.html { redirect_to levels_path, notice: 'Level number was successfully destroyed.' }
  end
end

private
 def level_params
   params.require(:level).permit(:number)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloodTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/index.html.erb
<h1>Glucose Levels</h1>
<h3>This is your blood glucose level app!</h3>

<h4> Today is: <%= today = Time.now.strftime("%Y-%m-%d") %></h4>

<h4> Your today's entries </h4>

<% if @levels.exists? %>
<table class="table-bordered">
  <tr>
    <td> level </td>
    <td> date </td>
  </tr>
  <% @levels.each do |level| %>
  <tr>
    <td id="levelNum"><%= link_to level.number, level_path(level) %></td>
    <td><%= level.date.strftime("%Y-%m-%d")%></td>
  </tr>
  <% end %>
</table>
<% else %>
<p> You dont have any entries for today yet </p>
<% end %>


<% if Level.all.where(date: today).count < 4 %>
<h5><%= link_to 'Add New Entry', new_level_path %></h5>
<% else %>
<p> Thanks, No more entries possible. You only have to enter blood level up to four times per day</p>
<% end %>

<div class="row">
  <div class="col-md-4">
    <h3>Daily Reports</h3>
    <h5> This report shows the current day you search for. </h5>
    <%= form_tag("/levels", method: "get") do %>
    <p>
      <%= label_tag(:q, "Search for daily report:") %>
      <%= date_field_tag :search_daily, params[:search_daily] %>
      <%= submit_tag "Search", :name => nil, :class => "daily" %>
    </p>
    <% end %>

<!-- if level1 exists show below table -->
    <% if @levels1 %>
    <table>
      <% @levels1.each do |level| %>
      <tr>
        <td><%= link_to level.number, level_path(level) %></td>
        <td><%= level.date.strftime("%Y-%m-%d") %></td>
      </tr>
      <% end %>
      <p> Average Daily is: <%= @levels1.average(:number) %></p>
      <p> Minimum Daily is: <%= @levels1.minimum(:number) %></p>
      <p> Maximum Daily is: <%= @levels1.maximum(:number) %></p>
    </table>
    <% end %>
  </div>

  <div class="col-md-4">
    <h3> Month To Date Reports</h3>
    <h5> This report shows the complete current month up to the end of the day you search for. </h5>
    <%= form_tag("/levels", method: "get") do %>
    <p>
      <%= label_tag(:q, "Search for Month to Date report:") %>
      <%= date_field_tag :search_month_to_date, params[:search_month_to_date] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
    <% end %>

    <!-- if level2 exists show below table -->
    <% if @levels2 %>
    <table>
      <% @levels2.each do |level| %>
      <tr>
        <td><%= link_to level.number, level_path(level) %></td>
        <td><%= level.date.strftime("%Y-%m-%d") %></td>
      </tr>
      <% end %>
      <p> Average Month To Date is: <%= @levels2.average(:number) %></p>
      <p> Minimum Month To Date is: <%= @levels2.minimum(:number) %></p>
      <p> Maximum Month To Date is: <%= @levels2.maximum(:number) %></p>
    </table>
    <% end %>
  </div>


  <div class="col-md-4">
    <h3> Monthly Reports</h3>
    <h5> This report shows the complete previous month of the day you search for. </h5>
    <%= form_tag("/levels", method: "get") do %>
    <p>
      <%= label_tag(:q, "Search for monthly report:") %>
      <%= date_field_tag :search_monthly, params[:search_monthly] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
    <% end %>

    <!-- if level3 exists show below table -->
    <% if @levels3 %>
    <table>
      <% @levels3.each do |level| %>
      <tr>
        <td><%= link_to level.number, level_path(level) %></td>
        <td><%= level.date.strftime("%Y-%m-%d") %></td>
      </tr>
      <% end %>
      <p> Average Monthly is: <%= @levels3.average(:number) %></p>
      <p> Minimum Monthly is: <%= @levels3.minimum(:number) %></p>
      <p> Maximum Monthly is: <%= @levels3.maximum(:number) %></p>
    </table>
    <% end %>
  </div>
</div>

app/views/levels/new.html.erb
<h1>New Blood level entries</h1>

<% if @level.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @level.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @level do |f| %>
  <%= f.label 'Number' %>
  <%= f.number_field(:number, in: 1..100) %>
  <%= f.button 'Submit', :class => 'btn btn-xs btn-success' %>
<% end %>

app/views/levels/show.html.erb
<h1><%= @level.number %></h1>
<h4><%= link_to 'Destroy', level_path(@level), method: :delete, data: { confirm: 'Are you sure?' } %></td>

<p><%= link_to "Return to home page", levels_path %></p>